apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana
  namespace: monitoring
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume-1
  namespace: monitoring
spec:
  storageClassName: grafana
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
  hostPath:
    path: "/mnt/data"

